server {
    listen       80;
    server_name  localhost;

    resolver 127.0.0.11 valid=30s;          # Docker DNS

    root   /usr/share/nginx/html;
    index  index.html;

    location / {
        try_files $uri /index.html;
    }

    # TradingView API proxy
    location /api/tv/ {
        proxy_pass https://screener-facade.tradingview.com/;
        proxy_ssl_server_name on;
        proxy_set_header Origin "https://www.tradingview.com";
        proxy_set_header Host screener-facade.tradingview.com;
    }

    # WebSocket proxy (handles both your app and the TradingView widget)
    location /ws/ {
        rewrite ^/ws/(.*) /$1 break;
        proxy_pass https://widgetdata.tradingview.com;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host widgetdata.tradingview.com;
        proxy_set_header Origin "https://www.tradingview.com";
        proxy_ssl_server_name on;
        resolver 127.0.0.11 valid=30s;
    }
}